from .fields import (
    SECTION_BODY,
    SECTION_HEADER,
    PAGES_FIELD,
    PAGE_RAW_TEXT_FIELD,
    INPUT_IDS_FIELD,
    ENTITY_GROUP_FIELD,
    WORD_FIELD,
    SCORE_FIELD
)
from .model_configs import (
    BASE_MODEL_NAME,
    MAX_TOKENS,
    AGGREGATION_STRATEGY,
    MODEL_PATH,
    REFERENCES_MIN_SCORE
)
