version: '3'
services:
  gc-redis:
    container_name: gc-redis
    hostname: gc-redis
    image: redis
    ports:
      - "6380:6380"
    command: --port 6380
    expose:
      - "6380"
    networks:
      - app-net
  gamechanger-ml-gpu:
    container_name: gc-ml-gpu
    image: gamechanger-ml-gpu
    build:
      context: ../../.
      dockerfile: gamechangerml/api/fastapi/rhel8.mlapp.Dockerfile
    deploy:
      resources:
        reservations:
          devices:
          - capabilities: [gpu]
            #runtime: nvidia
            #command: nvidia-smi
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - "../../gamechangerml/models:/opt/app-root/src/gamechangerml/models"
      - "../../gamechangerml/corpus:/opt/app-root/src/gamechangerml/corpus"
      - "../../gamechangerml/data:/opt/app-root/src/gamechangerml/data"
      - ~/.aws/:/.aws
    depends_on:
      - gc-redis
    networks:
      - app-net

networks:
  app-net:
    name: "${COMPOSE_PROJECT_NAME:-gc-dev}-network"
